package generator

import (
	_ "embed"
	"fmt"
	"go/types"
	"os"
	"regexp"
	"strings"
	"text/template"

	"github.com/lkebin/repository/parser"
	impt "golang.org/x/tools/imports"
)

//go:embed templates/find.gotpl
var findTpl string

//go:embed templates/exists.gotpl
var existsTpl string

//go:embed templates/count.gotpl
var countTpl string

//go:embed templates/create.gotpl
var createTpl string

//go:embed templates/update.gotpl
var updateTpl string

//go:embed templates/delete.gotpl
var deleteTpl string

//go:embed templates/query.gotpl
var queryTpl string

var templates = template.Must(
	template.New("").Funcs(funcMap()).
		Parse(findTpl + existsTpl + countTpl + createTpl + updateTpl + deleteTpl + queryTpl),
)

func GenerateRepositoryImplements(spec *RepositorySpecs) ([]byte, error) {
	implName := fmt.Sprintf("%sImpl", strings.ToLower(spec.Name[:1])+spec.Name[1:])
	var tpl = &strings.Builder{}
	tpl.WriteString(fmt.Sprintf("// Code generated by \"repository %s\"; DO NOT EDIT.\n", strings.Join(os.Args[1:], " ")))
	tpl.WriteString(fmt.Sprintf("package %s\n", spec.Pkg.Name()))
	tpl.WriteString("\n")
	// Imports
	tpl.WriteString("import (\n")
	imports := make(map[string]any)
	imports["github.com/jmoiron/sqlx"] = nil
	imports["database/sql"] = nil
	imports["fmt"] = nil
	for _, v := range spec.Methods {
		for i := range v.Signature().Params().Len() {
			importPath := lookupPkgPath(v.Signature().Params().At(i).Type())
			if importPath != "" && importPath != spec.Pkg.Path() {
				imports[importPath] = nil
			}
		}
		for i := range v.Signature().Results().Len() {
			importPath := lookupPkgPath(v.Signature().Results().At(i).Type())
			if importPath != "" && importPath != spec.Pkg.Path() {
				imports[importPath] = nil
			}
		}
	}
	for k := range imports {
		tpl.WriteString(fmt.Sprintf("\t\"%s\"\n", k))
	}
	tpl.WriteString(")\n")
	tpl.WriteString("\n")

	tpl.WriteString(fmt.Sprintf("type %s struct {\n", implName))
	tpl.WriteString("\tdb sqlx.ExtContext\n")
	tpl.WriteString("}\n")
	tpl.WriteString("\n")

	// New
	tpl.WriteString(fmt.Sprintf("func New%s(db sqlx.ExtContext) %s {\n", spec.Name, spec.Name))
	tpl.WriteString(fmt.Sprintf("\treturn &%s{db: db}\n", implName))
	tpl.WriteString("}\n")
	tpl.WriteString("\n")

	modelNamed := lookupNamed(spec.EmbeddedTypeArgs[0])
	if modelNamed == nil {
		return nil, fmt.Errorf("parse model error")
	}

	model := getModelFromNamed(modelNamed)
	if model == nil {
		return nil, fmt.Errorf("get model from named error")
	}

	// Implements
	for _, v := range spec.Methods {
		fn, err := genFuncImpl(implName, model, v, spec)
		if err != nil {
			return nil, err
		}
		tpl.WriteString(fn)
		tpl.WriteString("\n")
	}

	return impt.Process("", []byte(tpl.String()), nil)
}

func genFuncImpl(implName string, model *ModelSpecs, m *types.Func, spec *RepositorySpecs) (string, error) {
	var tpl = &strings.Builder{}
	fn := FuncImpl{
		Name:       m.Name(),
		Receiver:   fmt.Sprintf("*%s", implName),
		Params:     m.Signature().Params(),
		Results:    m.Signature().Results(),
		TableName:  ToSnakeCase(model.Name),
		Model:      model,
		Repository: spec,
	}

	pt, err := parser.NewPartTree(m.Name())
	if err != nil {
		return "", err
	}
	fn.PartTree = pt

	switch {
	case m.Name() == "Create":
		if err := templates.ExecuteTemplate(tpl, "Create", fn); err != nil {
			return "", fmt.Errorf("create template execute error: %w", err)
		}
	case m.Name() == "Update":
		pkColumn := lookupPkColumn(model)
		if pkColumn == nil {
			return "", fmt.Errorf("pk column not found")
		}
		fn.WhereColumns = []*Column{{Name: pkColumn.Name}}
		if err := templates.ExecuteTemplate(tpl, "Update", fn); err != nil {
			return "", fmt.Errorf("update template execute error: %w", err)
		}
	case m.Name() == "Count":
		if err := templates.ExecuteTemplate(tpl, "Count", fn); err != nil {
			return "", fmt.Errorf("count all template execute error: %w", err)
		}
	case m.Name() == "FindById":
		pkColumn := lookupPkColumn(model)
		if pkColumn == nil {
			return "", fmt.Errorf("pk column not found")
		}
		pt, err := parser.NewPartTree("FindBy" + pkColumn.Property)
		if err != nil {
			return "", err
		}
		fn.PartTree = pt
		if err := templates.ExecuteTemplate(tpl, "FindBy", fn); err != nil {
			return "", fmt.Errorf("find by id template execute error: %w", err)
		}

	case m.Name() == "FindAll":
		if err := templates.ExecuteTemplate(tpl, "FindAll", fn); err != nil {
			return "", fmt.Errorf("find all template execute error: %w", err)
		}
	case m.Name() == "ExistsById":
		pkColumn := lookupPkColumn(model)
		if pkColumn == nil {
			return "", fmt.Errorf("pk column not found")
		}
		pt, err := parser.NewPartTree("ExistsBy" + pkColumn.Property)
		if err != nil {
			return "", err
		}
		fn.PartTree = pt
		if err := templates.ExecuteTemplate(tpl, "ExistsBy", fn); err != nil {
			return "", fmt.Errorf("exists template execute error: %w", err)
		}

	case m.Name() == "DeleteById":
		pkColumn := lookupPkColumn(model)
		if pkColumn == nil {
			return "", fmt.Errorf("pk column not found")
		}
		pt, err := parser.NewPartTree("DeleteBy" + pkColumn.Property)
		if err != nil {
			return "", err
		}
		fn.PartTree = pt
		if err := templates.ExecuteTemplate(tpl, "DeleteBy", fn); err != nil {
			return "", fmt.Errorf("delete template execute error: %w", err)
		}

	case m.Name() == "Query":
		if err := templates.ExecuteTemplate(tpl, "Query", fn); err != nil {
			return "", fmt.Errorf("query template execute error: %w", err)
		}

	default:
		if pt.Subject.IsCount {
			if err := templates.ExecuteTemplate(tpl, "CountBy", fn); err != nil {
				return "", fmt.Errorf("count template execute error: %w", err)
			}
		} else if pt.Subject.IsExists {
			if err := templates.ExecuteTemplate(tpl, "ExistsBy", fn); err != nil {
				return "", fmt.Errorf("exists template execute error: %w", err)
			}
		} else if pt.Subject.IsDelete {
			if err := templates.ExecuteTemplate(tpl, "DeleteBy", fn); err != nil {
				return "", fmt.Errorf("delete template execute error: %w", err)
			}
		} else {
			if err := templates.ExecuteTemplate(tpl, "FindBy", fn); err != nil {
				return "", fmt.Errorf("find template execute error: %w", err)
			}
		}
	}

	return tpl.String(), nil
}

type FuncImpl struct {
	Receiver      string
	Name          string
	TableName     string
	Params        *types.Tuple
	Results       *types.Tuple
	Model         *ModelSpecs
	Repository    *RepositorySpecs
	SelectColumns []*Column
	WhereColumns  []*Column
	PartTree      *parser.PartTree
}

type Column struct {
	Name     string
	Property string
}

var (
	snakeRe1 = regexp.MustCompile("([a-z])([A-Z])")
	snakeRe2 = regexp.MustCompile("([a-zA-Z])([0-9])")
	snakeRe3 = regexp.MustCompile("([0-9])([A-Z])")
)

func ToSnakeCase(s string) string {
	s = snakeRe1.ReplaceAllString(s, "${1}_${2}")
	s = snakeRe2.ReplaceAllString(s, "${1}_${2}")
	s = snakeRe3.ReplaceAllString(s, "${1}_${2}")
	return strings.ToLower(s)
}
