// Code generated by `repository -type=UserRepository,UserUuidRepository`, DO NOT EDIT.
package testdata

import (
	"context"
	"database/sql"
	"github.com/jmoiron/sqlx"
	"github.com/lkebin/repository"
	"github.com/lkebin/repository/testdata"
)

type userUuidRepositoryImpl struct {
	db sqlx.ExtContext
}

func NewUserUuidRepository(db sqlx.ExtContext) UserUuidRepository {
	return &userUuidRepositoryImpl{db: db}
}

func (r *userUuidRepositoryImpl) Create(ctx context.Context, model *testdata.UserUuid) (*testdata.UserUuid, error) {
	_, err := r.db.ExecContext(ctx, "INSERT INTO `user_uuid` (`id`, `name`, `birthday`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?)", model.Id, model.Name, model.Birthday, model.CreatedAt, model.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return r.Find(ctx, model.Id)
}

func (r *userUuidRepositoryImpl) Delete(ctx context.Context, id repository.ID) error {
	_, err := r.db.ExecContext(ctx, "DELETE FROM `user_uuid` WHERE `id` = ?", id)
	if err != nil {
		return err
	}
	return nil
}

func (r *userUuidRepositoryImpl) Find(ctx context.Context, id repository.ID) (*testdata.UserUuid, error) {
	var m testdata.UserUuid
	err := r.db.QueryRowxContext(ctx, "SELECT `id`, `name`, `birthday`, `created_at`, `updated_at` FROM `user_uuid` WHERE `id` = ?", id).StructScan(&m)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &m, nil
}

func (r *userUuidRepositoryImpl) Update(ctx context.Context, model *testdata.UserUuid) error {
	_, err := r.db.ExecContext(ctx, "UPDATE `user_uuid` SET `name` = ?, `birthday` = ?, `created_at` = ?, `updated_at` = ?  WHERE `id` = ?", model.Name, model.Birthday, model.CreatedAt, model.UpdatedAt, model.Id)
	if err != nil {
		return nil, err
	}

	return nil
}

func (r *userUuidRepositoryImpl) FindByName(ctx context.Context, name string) (*testdata.UserUuid, error) {
	var m testdata.UserUuid
	err := r.db.QueryRowxContext(ctx, "SELECT `id`, `name`, `birthday`, `created_at`, `updated_at` FROM `user_uuid` WHERE `name` = ?", name).StructScan(&m)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &m, nil
}
